name: Weather Workflow
on: workflow_dispatch
jobs:
  start-application:
    runs-on: ubuntu-latest
    steps:
    - name: Run the app
      run: npm start
      working-directory: /home/runner/work/weather-report/weather-report/
