name: Weather Workflow
on: workflow_dispatch
jobs:
  start-application:
    runs-on: ubuntu-latest
    steps:
    - name: Indicate the directory
      uses: ./
    - name: Run the app
      run: npm start
