name: Weather Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print to console
      run: echo Hello workflow!
    - name: Run the weather
      run: npm start
