name: Weather Workflow
on: workflow_dispatch
jobs:
  run_application:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependancies
        run: npm install
      - name: Run application
        run: npm run start
